import type { Certification, Education, Experience, Profile } from "./types.js";
const text = (v: unknown): string | null => typeof v === "string" && v.trim() ? v.trim() : null;
const arr = (v: unknown): unknown[] => Array.isArray(v) ? v : [];
const date = (v: unknown): string | null => { const s = text(v); if (!s) return null; const m = s.match(/(\d{4})(?:[-/.](\d{1,2}))?/); return m ? `${m[1]}-${(m[2] ? m[2].padStart(2, "0") : "01")}` : null; };
const uniqueStrings = (v: unknown): string[] => [...new Set(arr(v).map(text).filter((x): x is string => Boolean(x)))];
function image(v: unknown) { if (!v || typeof v !== "object") return null; const x = v as Record<string, unknown>; const url = text(x.url) ?? text(x.src); return url ? { url, width: typeof x.width === "number" ? x.width : null, height: typeof x.height === "number" ? x.height : null } : null; }
export function normalizeProfile(raw: unknown, url: string): Profile {
  const x = raw && typeof raw === "object" ? raw as Record<string, unknown> : {};
  const pick = (...keys: string[]) => keys.map(k => x[k]).find(v => v !== undefined && v !== null);
  const experience: Experience[] = arr(pick("experience", "positions")).map(v => { const e = (v && typeof v === "object" ? v : {}) as Record<string, unknown>; return { title:text(e.title), company:text(e.company ?? e.companyName), company_url:text(e.company_url ?? e.companyUrl), location:text(e.location), description:text(e.description), start_date:date(e.start_date ?? e.startDate), end_date:date(e.end_date ?? e.endDate), is_current:typeof e.is_current === "boolean" ? e.is_current : typeof e.isCurrent === "boolean" ? e.isCurrent : null }; });
  const education: Education[] = arr(pick("education", "schools")).map(v => { const e = (v && typeof v === "object" ? v : {}) as Record<string, unknown>; return { school:text(e.school ?? e.schoolName), school_url:text(e.school_url ?? e.schoolUrl), degree:text(e.degree), field:text(e.field ?? e.fieldOfStudy), start_date:date(e.start_date ?? e.startDate), end_date:date(e.end_date ?? e.endDate), description:text(e.description) }; });
  const certifications: Certification[] = arr(x.certifications).map(v => { const e = (v && typeof v === "object" ? v : {}) as Record<string, unknown>; return { name:text(e.name), issuer:text(e.issuer), issued_date:date(e.issued_date ?? e.issuedDate), expiry_date:date(e.expiry_date ?? e.expiryDate), credential_id:text(e.credential_id ?? e.credentialId), credential_url:text(e.credential_url ?? e.credentialUrl) }; });
  return { url, public_identifier: url.split("/").pop() ?? "", name:text(pick("name", "fullName")), headline:text(pick("headline", "title")), location:text(x.location), about:text(pick("about", "summary")), profile_image:image(pick("profile_image", "profileImage", "image")), experience, education, skills:uniqueStrings(x.skills), certifications, languages:uniqueStrings(x.languages) };
}
export function availability(profile: Profile): { fields_available: string[]; fields_unavailable: string[]; partial: boolean } { const fields = ["name","headline","location","about","profile_image","experience","education","skills","certifications","languages"]; const available = fields.filter(k => { const v = profile[k as keyof Profile]; return Array.isArray(v) ? v.length > 0 : v !== null && v !== ""; }); return { fields_available:available, fields_unavailable:fields.filter(x => !available.includes(x)), partial:available.length < fields.length }; }
